language: python
services:
   - docker
python:
   - "2.7"
install:
   - make deps
script:
   - make lint
   - make test
   - make docker_build

deploy:
  provider: heroku
  app: lit-harbor-41646
  api_key: ${c6e492c8-553d-41da-bd63-7abb0997293f}
